### PR TITLE
Do not delete users although they are last project admin

### LINKED ISSUE #114: [Bug]: Delete users although still project admin
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which use case does this bug relate to?

#30

### What happened?

When I delete a user in the backend and the user is still the only admin in any project, then the project has no active admin anymore which prevent certain changes in the project. 

### Steps to reproduce

1. Make one user admin of a project
2. Delete this user account

### What did you expect?

I would expect, that a `FAILED_PRECONDITION` error is thrown when a user wants to delete its account although the user is still the only admin in any project. 

### Anything else?

We still need to discuss, 
- whether this only applies for active projects or any projects
- whether we throw an error or automatically update some random project member to the project admin (consider the case, when this user is the only member &rarr; maybe delete the project as well in this case)

The result of this discussion and the final decision should be reflected in the API documentation.

### PR DESCRIPTION
**Pull request by Merseleo**
Closes #114 

## What I have made

- I extended the project member repo with filters, that no users that are soft deleted and still in a project are listed when requesting the project members or admins and adapted the tests (+ further refactoring and adding of missing tests)
- I added a check, that ensures that the user to be soft-deleted is not the last project admin in any project
- I created a new project access rule `isNotLastProjectAdmin`. Actually this is not the best location, as this is actually not for an access, but I was not sure where else to place this helper function I introduced, because we often check, whether a user is not the last project admin and if so, throw a FailedPreconditionException. I am open for suggestions where we could place this helper instead.

## Checklist

Either tick or cross out the items that do not apply (using \~\~example text\~\~) and give a reason why the item does
not apply.

- [x] I have updated the documentation accordingly and commented my code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] (for reviewer) I have checked the implementation against the requirements

### CODE REVIEW

File: src/main/kotlin/se/uulm/snowballr/backend/repository/association/ProjectMemberTableRepo.kt [hunk 1]
```diff
@@ -102,6 +108,15 @@ interface IProjectMemberTableRepo {
 class ProjectMemberTableRepo(
     private val db: IDatabase,
 ) : IProjectMemberTableRepo {
+    /**
+     * Retrieves a list of UUID from these users that are marked as deleted.
+     *
+     * @return A list of UUIDs representing users that are soft-deleted.
+     */
+    private fun getSoftDeletedUsers(): List<UUID> = UserTable
```
Comment (domienderle) [inline src/main/kotlin/se/uulm/snowballr/backend/repository/association/ProjectMemberTableRepo.kt]: What do you think of `getSoftDeletedUserIds` since we don't really query the users but the IDs?

File: src/main/kotlin/se/uulm/snowballr/backend/service/accessrules/ProjectAccessRule.kt [hunk 2]
```diff
@@ -62,6 +63,25 @@ fun isProjectAdmin(projectMemberRepo: IProjectMemberTableRepo) = AccessRule<UUID
     projectAdmins.any { it.userId == requester.id }
 }
 
+/**
+ * Check whether the user is the last project admin of a specific project; otherwise, throws a [FailedPreconditionException].
```
Comment (domienderle) [inline src/main/kotlin/se/uulm/snowballr/backend/service/accessrules/ProjectAccessRule.kt]:
```suggestion
 * Check whether the user is not the last project admin of a specific project; otherwise, throws a [FailedPreconditionException].
```
We check whether the user is not the last project admin and only throw if they are the last project admin.

**Review by domienderle — CHANGES_REQUESTED** [review]
Good work. I only found two little changes.

About the positioning of the rule:
I see your point that it is not really an access rule. We could introduce something like condition checks or use case checks later. But I don't see the necessity at the moment and since the check is syntactically the same as the access rules and it differs only on a logical level, I would keep it there for the moment. If we encounter more of this condition checks at a later point in time we can still refactor it.

File: src/main/kotlin/se/uulm/snowballr/backend/service/accessrules/ProjectAccessRule.kt (hunk 2 above)
Comment (Merseleo) [reply src/main/kotlin/se/uulm/snowballr/backend/service/accessrules/ProjectAccessRule.kt]: You are right, good catch. I started this method the other way around and noticed I does not make sense and inverted the functionality without adapting the comment.

File: src/main/kotlin/se/uulm/snowballr/backend/repository/association/ProjectMemberTableRepo.kt (hunk 1 above)
Comment (Merseleo) [reply src/main/kotlin/se/uulm/snowballr/backend/repository/association/ProjectMemberTableRepo.kt]: Actually better, thank you for the suggestion 👍

**Review by Merseleo — COMMENTED** [review]
Thank you for the review and your opinion. I think it is the best solution to declare this check as access check and if we notice some more similar "problems" think about a solution.

**Review by domienderle — APPROVED** [review]
Good work.
