### PR TITLE
Incorrect checks for the status input when updating a project

### LINKED ISSUE #314: [Bug]: No check for the status input when updating a project
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which use case does this bug relate to?

#64

### What happened?

When I use the `UpdateProject` call to update the status, then it is only checked whether the new status is not `PROJECT_STATUS_DELETED`, but theoretically I can set a project from active locked to active using this call.

### Steps to reproduce

/

### What did you expect?

Actually the server should override active and active locked with the correct version, when these statuses are selected.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mowi12**
Closes #314 

## What I have made

- Added `isProjectLocked()` function in `projectTableRepo` + tests
- Updated `updateProject()` function in `projectService` + tests
  - Removed status checks from `projectTableRepo`'s `updateProject()` function

## Checklist

Either tick or cross out the items that do not apply (using \~\~example text\~\~) and give a reason why the item does
not apply.

- [x] I have updated the documentation accordingly and commented my code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] (for reviewer) I have checked the implementation against the requirements

### CODE REVIEW

File: src/main/kotlin/se/uulm/snowballr/backend/repository/ProjectTableRepo.kt [hunk 1]
```diff
@@ -88,12 +94,24 @@ interface IProjectTableRepo {
...
      * @return The updated [Project] object reflecting the changes from the [request].
      */
-    suspend fun updateProject(request: GrpcProject.Update, projectStatus: ProjectStatus): Project
+    suspend fun updateProject(request: GrpcProject.Update): Project
+
+    /**
+     * Checks if the project with the given [projectId] is locked.
+     *
+     * A project is considered **locked** if at least one [ProjectPaper] is associated with it that has at least one
+     * [Review] linked to it.
```
Comment (Merseleo) [inline src/main/kotlin/se/uulm/snowballr/backend/repository/ProjectTableRepo.kt]:
```suggestion
     * A project is considered **locked** if at least one [ProjectPaper] with at least one [Review] is associated with this project.
```

Comment (Merseleo) [reply src/main/kotlin/se/uulm/snowballr/backend/repository/ProjectTableRepo.kt]: Or do you have any other idea? Because in my opinion it is quite hard to understand this sentence.

File: src/test/kotlin/se/uulm/snowballr/backend/repository/ProjectTableRepoTest.kt [hunk 2]
```diff
@@ -181,9 +188,9 @@ class ProjectTableRepoTest : RepositoryTest(arrayOf(ProjectTable, ProjectMemberT
         fun `When a project is active and updated, then only the fields specified in the field mask are updated and the updated project is returned`(
```
Comment (Merseleo) [inline src/test/kotlin/se/uulm/snowballr/backend/repository/ProjectTableRepoTest.kt]:
```suggestion
        fun `When a project is updated, then only the fields specified in the field mask are updated and the updated project is returned`(
```

Comment (Merseleo) [reply src/test/kotlin/se/uulm/snowballr/backend/repository/ProjectTableRepoTest.kt]: The status is not important anymore, right?

File: src/test/kotlin/se/uulm/snowballr/backend/repository/ProjectTableRepoTest.kt [hunk 3]
```diff
@@ -464,4 +387,37 @@ class ProjectTableRepoTest : RepositoryTest(arrayOf(ProjectTable, ProjectMemberT
                 }
             }
     }
+
+    @Nested
+    inner class IsProjectLocked {
+        @Test
+        fun `When a project has no project papers, then the project is not locked`() = runTest {
+            val projectId =
+                insertProjectAndGetId(status = ProjectStatus.PROJECT_STATUS_ACTIVE, createdBy = testUserId)
```
Comment (Merseleo) [inline src/test/kotlin/se/uulm/snowballr/backend/repository/ProjectTableRepoTest.kt:396]: Actually it doesn't matter which status your project have (at least regarding your comment).

File: src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt [hunk 4]
```diff
@@ -167,20 +170,106 @@ class ProjectService(
...
+            }
+        }
+    }
+
+    /**
+     * Determines the final status of a project based on the current status and the requested status.
+     *
+     * If the requested status is ACTIVE or ACTIVE_LOCKED, it checks if the project has any papers with reviews. If so,
+     * the project is locked. Otherwise, it is set to ACTIVE.
+     * Else, the requested status is returned.
```
Comment (Merseleo) [inline src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt]:
```suggestion
     * If the requested status is ACTIVE or ACTIVE_LOCKED, it checks if the project has any papers with reviews. If so,
     * the project is ACTIVE_LOCKED; otherwise, it is set to ACTIVE.
     * If the requested status is not an active status, it is directly returned.
```

File: src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt [hunk 5]
```diff
@@ -167,20 +170,106 @@ class ProjectService(
...
+     *
+     * @param projectId The ID of the project to be updated.
+     * @param requestedStatus The status that is requested for the project.
+     * @return The final status of the project.
+     */
+    private suspend fun determineFinalStatus(projectId: UUID, requestedStatus: ProjectStatus): ProjectStatus {
```
Comment (Merseleo) [inline src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt]: What about `computeEffectiveProjectStatus`?

File: src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt [hunk 6]
```diff
@@ -167,20 +170,106 @@ class ProjectService(
...
+        fieldMask: List<String>,
+    ) {
+        require(!(fieldMask.contains("project.status") && requestedStatus == ProjectStatus.PROJECT_STATUS_DELETED)) {
+            "The project status cannot be set to DELETED via the update method. Use SoftDeleteProject instead."
         }
 
-        repo.updateProject(request, project.status).toGrpcProject()
+        when (currentStatus) {
+            ProjectStatus.PROJECT_STATUS_DELETED -> {
+                throw FailedPreconditionException("The update failed because the project has been deleted.")
```
Comment (Merseleo) [inline src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt]:
```suggestion
                throw FailedPreconditionException("The project has been deleted and can therefore not be updated anymore.")
```

File: src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt [hunk 7]
```diff
@@ -167,20 +170,106 @@ class ProjectService(
...
+            }
+
+            ProjectStatus.PROJECT_STATUS_ARCHIVED -> {
+                val isOnlyStatusUpdate = fieldMask.size == 1 && fieldMask.contains("project.status")
+                if (!isOnlyStatusUpdate) {
+                    throw FailedPreconditionException(
+                        "For an archived project, only the 'status' field can be updated.",
```
Comment (Merseleo) [inline src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt]:
```suggestion
                        "The project is archived and therefore only the 'status' field can be updated.",
```
What do you think of all these suggestions? Better or worse?

File: src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt [hunk 8]
```diff
@@ -167,20 +170,106 @@ class ProjectService(
...
+                require(
+                    requestedStatus == ProjectStatus.PROJECT_STATUS_ACTIVE ||
+                        requestedStatus == ProjectStatus.PROJECT_STATUS_ACTIVE_LOCKED,
+                ) { "An archived project can only be unarchived by setting its status to ACTIVE or ACTIVE_LOCKED." }
+            }
+
+            ProjectStatus.PROJECT_STATUS_ACTIVE_LOCKED -> {
+                val isChangingSettings = fieldMask.any { it.startsWith("project.settings.") }
+                require(!isChangingSettings) {
+                    "The project's settings cannot be modified while it is locked."
```
Comment (Merseleo) [inline src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt]:
```suggestion
                    "The project is locked and therefore no project settings can be modified."
```
But I thought that only SLR settings cannot be changed? The fetchers should be changeable, right? And the snowballing type?

File: src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt [hunk 9]
```diff
@@ -158,19 +170,24 @@ class UpdateProjectTest : MainServiceTest() {
...
             assertThrows<FailedPreconditionException> { mainService.updateProject(request) }
         }
 
-    @Test
-    fun `When a server admin updates a deleted project, then a FailedPreconditionException is thrown`() = runTest {
+    @ParameterizedTest
+    @CsvSource(
+        value = ["PROJECT_STATUS_ACTIVE", "PROJECT_STATUS_ACTIVE_LOCKED"],
+    )
+    fun `When a server admin updates an archived project to an active status, then no exception is thrown`(
```
Comment (Merseleo) [inline src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt:182]: Maybe you could also verify that the status of the returned project is correct, what do you think? (same for other tests: verify, that the update was successful?) Or do you think this isn't necessary as this should be correct because of the repo function?

File: src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt [hunk 10]
```diff
@@ -180,20 +197,91 @@ class UpdateProjectTest : MainServiceTest() {
...
-    fun `When a project admin updates a deleted project, then a FailedPreconditionException is thrown`() = runTest {
-        val user = DataBuilder.createExampleUser(role = UserRole.USER_ROLE_DEFAULT)
-        val project = DataBuilder.createExampleProject(
-            status = ProjectStatus.PROJECT_STATUS_DELETED,
+    fun `When a server admin updates the status of an archived project to an unallowed status, then an IllegalArgumentException is thrown`() =
+        runTest {
+            val user = DataBuilder.createExampleUser(role = UserRole.USER_ROLE_ADMIN)
+            val project = DataBuilder.createExampleProject(status = ProjectStatus.PROJECT_STATUS_ARCHIVED)
+            val updatedProject =
+                DataBuilder.createExampleProject(id = project.id, status = ProjectStatus.PROJECT_STATUS_ARCHIVED)
```
Comment (Merseleo) [inline src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt]: Why is this an error? Actually nothing should happen right? If you archive an archived project, nothing should happen?

File: src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt [hunk 11]
```diff
@@ -132,24 +129,39 @@ class UpdateProjectTest : MainServiceTest() {
             coEvery { projectRepoMock.getProjectById(project.id) } returns Result.success(project)
             coEvery { projectMemberRepoMock.getAllProjectAdmins(project.id) } returns emptyList()
 
-            assertThrows<FailedPreconditionException> { mainService.updateProject(request) }
+            assertThrows<IllegalArgumentException> { mainService.updateProject(request) }
```
Comment (Merseleo) [inline src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt:132]: If you adapt this, then please the test description as well.

File: src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt [hunk 12]
```diff
@@ -180,20 +197,91 @@ class UpdateProjectTest : MainServiceTest() {
...
+                .newBuilder()
+                .setProject(updatedProject.toGrpcProject())
+                .setMask(updateFieldMask)
+                .build()
+
+            mockCurrentUser(user)
+            coEvery { projectRepoMock.getProjectById(project.id) } returns Result.success(project)
+            coEvery { projectMemberRepoMock.getAllProjectAdmins(project.id) } returns emptyList()
+
+            assertThrows<IllegalArgumentException> { mainService.updateProject(request) }
```
Comment (Merseleo) [inline src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt]: This is not the same Exception like in the test description.

File: src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt [hunk 13]
```diff
@@ -202,8 +290,38 @@ class UpdateProjectTest : MainServiceTest() {
...
+                .newBuilder()
+                .setProject(updatedProject.toGrpcProject())
+                .setMask(updateFieldMask)
+                .build()
+
+            mockCurrentUser(user)
+            coEvery { projectRepoMock.getProjectById(project.id) } returns Result.success(project)
+            coEvery { projectMemberRepoMock.getAllProjectAdmins(project.id) } returns emptyList()
+
+            assertThrows<IllegalStateException> { mainService.updateProject(request) }
```
Comment (Merseleo) [inline src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt:328]: Same here: this is not the exception in the test description.

**Review by Merseleo — CHANGES_REQUESTED** [review]
Great work, I didn't find a big issue, just small things (but some).

And in general there is one "problem" with your current implementation. The `IllegalArgumentException`s are correctly thrown and also converted to `INVALID_ARGUMENT` status codes, however their messages are not sent as well, so if you want to delete a project using `UpdateProject` then you get an empty `INVALID_ARGUMENT` and the reason is only logged in the backend but not sent to the frontend. Maybe extend the ´handleException` function in the `ExceptionInterceptor`?

File: src/main/kotlin/se/uulm/snowballr/backend/repository/ProjectTableRepo.kt (hunk 1 above)
Comment (mowi12) [reply src/main/kotlin/se/uulm/snowballr/backend/repository/ProjectTableRepo.kt]: I think your sentence is quite clear!

File: src/test/kotlin/se/uulm/snowballr/backend/repository/ProjectTableRepoTest.kt (hunk 2 above)
Comment (mowi12) [reply src/test/kotlin/se/uulm/snowballr/backend/repository/ProjectTableRepoTest.kt]: Yes, you're right. The repo call does no longer validate the status.

File: src/test/kotlin/se/uulm/snowballr/backend/repository/ProjectTableRepoTest.kt (hunk 3 above)
Comment (mowi12) [reply src/test/kotlin/se/uulm/snowballr/backend/repository/ProjectTableRepoTest.kt:396]: Yes, that's right. I added a note in the documentation of this function which explains, that this functions always returns `true` or `false` but has to be interpreted correctly.
Which means, that the answers only make sense if the status is active or active locked, in any other case, these answers don't have any strength regarding their meaning.

File: src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt (hunk 5 above)
Comment (mowi12) [reply src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt]: ChatGPT gave me the same ideas. But I think determine is the better word.

File: src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt (hunk 7 above)
Comment (mowi12) [reply src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt]: Better

File: src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt (hunk 8 above)
Comment (mowi12) [reply src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt]: You're right. But what exactly are the SLR settings?

Comment (mowi12) [reply src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt]: After asking in the devs channel, all current settings are slr settings.

File: src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt (hunk 9 above)
Comment (mowi12) [reply src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt:182]: As you said. It shouldn't be necessary as the repo layer is tested and we assume that they do work.

File: src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt (hunk 10 above)
Comment (mowi12) [reply src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt]: Then this test case can be removed, as there is no "unallowed" status which could throw an `IllegalArgumentException`. Any active status is allowed, deleted is another exception, unspecified is already catched by the validator.

Comment (mowi12) [reply src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt]: I updated the logic in the service implementation and added a new test case which checks if the status stays the same.

Comment (mowi12) [reply src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt]: What about the deleted case?
Should it be allowed to update an deleted project to deleted?
Would be the same logic here.

File: src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt (hunk 11 above)
Comment (mowi12) [reply src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt:132]: I thought we said its a `FailedPreconditionException` ...

the arguments are valid, but the state doesn't allow it, as it is stated in the gPRC documentation.
Illegal argument would state that the arguments are invalid in any case, which is wrong.

File: src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt (hunk 5 above)
Comment (Merseleo) [reply src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt]: I agree.

File: src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt (hunk 8 above)
Comment (Merseleo) [reply src/main/kotlin/se/uulm/snowballr/backend/service/ProjectService.kt]: Yeah, and your updated comment and error message are better now, imo.

File: src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt (hunk 10 above)
Comment (Merseleo) [reply src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt]: No, because in a deleted project nothing can be changed?! But you forgot to adapt the `require` logic in the check, whether the status is set to `DELETED`. Please update this as well, because if you set the status of any project to `DELETED`, you get an `INVALID_ARGUMENT` error without any description.

File: src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt (hunk 11 above)
Comment (Merseleo) [reply src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt:132]: My point was: No matter what exception you choose: the exception you throw and expect should be same as in the test description.

**Review by Merseleo — CHANGES_REQUESTED** [review]
Ok, I think there are only two little things left, please fix them and then you can merge!

PS: Please fix the tests before, so the merge can be performed automatically if I approve.

File: src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt (hunk 10 above)
Comment (mowi12) [reply src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt]: Everything should be fine now.

File: src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt (hunk 11 above)
Comment (mowi12) [reply src/test/kotlin/se/uulm/snowballr/backend/service/project/UpdateProjectTest.kt:132]: Should be fixed now.

**Review by Merseleo — APPROVED** [review]
I did not found any issues, so I think its ready to be merged!
