### PR TITLE
Resolve missing checks validations based on api definition

### LINKED ISSUE #389: [Bug]: Resolve missing Checks / Validations based on API Definition
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which use case does this bug relate to?

_No response_

### What happened?

@Merseleo and I validated the errors defined in the API definition and found some mishaps.

### Steps to reproduce

1. Look a look at the API definition and compare to the commits

### What did you expect?

The server should check or return the right errors.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mowi12**
Closes #389 

## What I have made

- Reordered some access checks
- Added checks
- Added some documentation

## Checklist

Either tick or cross out the items that do not apply (using \~\~example text\~\~) and give a reason why the item does
not apply.

- [x] I have updated the documentation accordingly and commented my code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] (for reviewer) I have checked the implementation against the requirements

### CODE REVIEW

File: src/main/kotlin/se/uulm/snowballr/backend/service/PaperService.kt [hunk 1]
```diff
@@ -75,6 +75,14 @@ class PaperService(
             throw NotFoundException(EntityType.PAPER, paperId.toString())
         }
 
+        if (repo.doesPaperExistByExternalId(request.paper.externalId)) {
+            throw DuplicateEntityException(
+                EntityType.PAPER,
+                request.paper.externalId,
+                identifierType = IdentifierType.EXTERNAL_ID,
+            )
```
Comment (luca-schlecker) [inline src/main/kotlin/se/uulm/snowballr/backend/service/PaperService.kt]: This check seems to cause an error when updating a paper, setting its external id to the one it already has.

**Review by luca-schlecker — CHANGES_REQUESTED** [review]
I think one edge-case is left

File: src/main/kotlin/se/uulm/snowballr/backend/service/PaperService.kt (hunk 1 above)
Comment (mowi12) [reply src/main/kotlin/se/uulm/snowballr/backend/service/PaperService.kt]: You're right. It should be fixed now!

Comment (luca-schlecker) [reply src/main/kotlin/se/uulm/snowballr/backend/service/PaperService.kt]: This is solved now, resolving.

**Review by luca-schlecker — DISMISSED** [review]
Everything I noticed seems to be resolved now. Rebase is needed and a wiki lint job is currently failing, after that this can be merged 👍

**Review by Slartibartfass2 — APPROVED** [review]
