### PR TITLE
Missing test assertions for register call

### LINKED ISSUE #142: [Bug]: Missing test assertions for `register` call
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which use case does this bug relate to?

_No response_

### What happened?

We currently do not test everything for the `register` call.

### Steps to reproduce

-

### What did you expect?

That everything for the `register` call is tested.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mowi12**
Closes #142 

## What I have made

- Improved `register` call test

## Checklist

Either tick or cross out the items that do not apply (using \~\~example text\~\~) and give a reason why the item does
not apply.

- [x] I have updated the documentation accordingly and commented my code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] (for reviewer) I have checked the implementation against the requirements

### CODE REVIEW

File: src/test/kotlin/se/uulm/snowballr/backend/service/user/RegisterTest.kt [hunk 1]
```diff
@@ -1,86 +1,109 @@
...
-        }
-
-        // Mock JWT key pair
-        val (privateKeyBase64, publicKeyBase64) = RandomKeyGenerator.generateKeyPair()
-        every { envReaderMock.env.encryption.jwtPrivateKeyBase64 } returns privateKeyBase64
-        every { envReaderMock.env.encryption.jwtPublicKeyBase64 } returns publicKeyBase64
-    }
+class RegisterTest : MainServiceTest() {
+    @Test
+    fun `When a user provides valid credentials, the user is registered successfully`() = testCoroutine {
```
Comment (Merseleo) [inline src/test/kotlin/se/uulm/snowballr/backend/service/user/RegisterTest.kt]:
```suggestion
    fun `When a user provides valid credentials, then the user is registered successfully`() = testCoroutine {
```

File: src/test/kotlin/se/uulm/snowballr/backend/service/user/RegisterTest.kt [hunk 2]
```diff
@@ -1,86 +1,109 @@
...
+        val testUser = DataBuilder.createExampleUser()
+        val userPassword = "AAbb__00"
+        val tokens = JwtTokens("accessToken", "refreshToken")
+
+        val request = Authentication.RegisterRequest.newBuilder().apply {
+            email = testUser.email
+            password = userPassword
+            firstName = testUser.firstName
+            lastName = testUser.lastName
+        }.build()
```
Comment (Merseleo) [inline src/test/kotlin/se/uulm/snowballr/backend/service/user/RegisterTest.kt]: Do you really need to build a complete request? You mock almost everything except for the password hashing
```suggestion
        val request = Authentication.RegisterRequest.newBuilder()
            .setPassword("AAbb__00")
            .build()
```

File: src/test/kotlin/se/uulm/snowballr/backend/service/user/RegisterTest.kt [hunk 3]
```diff
@@ -1,86 +1,109 @@
...
     }
 
     @Test
     fun `When a user already exists, then an exception is thrown`() = testCoroutine {
+        val cookiesMap = mutableMapOf<String, String?>()
+
+        // Create a new context with cookiesMap and run code inside it
+        val initialContext = Context.current()
+            .withValue(GrpcContext.COOKIES_TO_SET_CONTEXT_KEY, cookiesMap)
+        initialContext.attach()
```
Comment (Merseleo) [inline src/test/kotlin/se/uulm/snowballr/backend/service/user/RegisterTest.kt:60]: This code snippet is used in every test. Can't you outsource this in a local setup / beforeEach function or in a separate function that can be called? Because at the moment your test functions are quite long.

File: src/test/kotlin/se/uulm/snowballr/backend/service/user/RegisterTest.kt [hunk 4]
```diff
@@ -1,86 +1,109 @@
...
+
         val request = Authentication.RegisterRequest.newBuilder().build()
 
         coEvery { userRepoMock.doesUserExistByEmail(any()) } returns false
         coEvery { userRepoMock.createUser(any(), any()) } throws Exception("Failed to create user")
```
Comment (Merseleo) [inline src/test/kotlin/se/uulm/snowballr/backend/service/user/RegisterTest.kt:90]: I think we have the `TestSpecificException` for such use cases.

**Review by Merseleo — CHANGES_REQUESTED** [review]
Only some minor things, so I think the test code could be shortened a bit to make it more readable, but I like that the cookie handling is done in the service layer now.

File: src/test/kotlin/se/uulm/snowballr/backend/service/user/RegisterTest.kt (hunk 2 above)
Comment (mowi12) [reply src/test/kotlin/se/uulm/snowballr/backend/service/user/RegisterTest.kt]: You're right. All of this can be removed.

File: src/test/kotlin/se/uulm/snowballr/backend/service/user/RegisterTest.kt (hunk 3 above)
Comment (mowi12) [reply src/test/kotlin/se/uulm/snowballr/backend/service/user/RegisterTest.kt:60]: Issue #133 removes the dummy user and already streamlines this process. As this will be done there, I will just keep the setup as it is, since it will be removed in this issue already.

File: src/test/kotlin/se/uulm/snowballr/backend/service/user/RegisterTest.kt (hunk 4 above)
Comment (mowi12) [reply src/test/kotlin/se/uulm/snowballr/backend/service/user/RegisterTest.kt:90]: Correct. This is also a thing I updated in #133.

Comment (Merseleo) [reply src/test/kotlin/se/uulm/snowballr/backend/service/user/RegisterTest.kt:90]: Then I hope you don't forget it in #145.

File: src/test/kotlin/se/uulm/snowballr/backend/service/user/RegisterTest.kt (hunk 3 above)
Comment (Merseleo) [reply src/test/kotlin/se/uulm/snowballr/backend/service/user/RegisterTest.kt:60]: Did not know that, but I agree that it is probably the best to find a solution in this PR.

**Review by Merseleo — COMMENTED** [review]
Although its a bug and you named the branch **`feat/...`** I think we are done 🚀

**Review by Merseleo — DISMISSED** [review]

**Comment by mowi12** [comment]
I know you already approved. But as you requested the changes to the login and logout service layer to return `Base.Nothing` I also did it for the request call.

**Review by Merseleo — APPROVED** [review]
Perfect, did not even notice this.
