### PR TITLE
Improper dummy user implementation

### LINKED ISSUE #180: [Bug]: Improper Dummy User Implementation
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which use case does this bug relate to?

#133

### What happened?

The authentication status is not set and there are still methods, which are not used.

### Steps to reproduce

1. Start backend with new flag
2. set authentication status call

### What did you expect?

To be authenticated

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mowi12**
Closes #180 

## What I have made

- Added status to context
- Removed unused code

## Checklist

Either tick or cross out the items that do not apply (using \~\~example text\~\~) and give a reason why the item does
not apply.

- [x] I have updated the documentation accordingly and commented my code
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~ not needed
- [ ] (for reviewer) I have checked the implementation against the requirements

### CODE REVIEW

File: src/main/kotlin/se/uulm/snowballr/backend/auth/JwtService.kt
Comment (domienderle) [inline src/main/kotlin/se/uulm/snowballr/backend/auth/JwtService.kt:1]: Do you think we should change the comments like that? Imo opinion the `:` should also be bolt, because imo **Note:** looks better than **Note**:

File: src/main/kotlin/se/uulm/snowballr/backend/db/Database.kt [hunk 1]
```diff
@@ -125,29 +125,40 @@ class Database(
...
 
     /**
-     * Initializes a dummy user in the database if the environment variable is set to use a dummy user
-     * and the dummy user does not already exist.
+     * Sets up a dummy user in the database if the environment configuration requires it.
      *
-     * The dummy user is created with predefined credentials and role, which can be used for testing purposes.
+     * This method checks if a dummy user is needed based on the environment settings. If so, it
+     * creates the dummy user if it does not already exist. If the dummy user is not needed, it
+     * deletes the existing dummy user from the database.
```
Comment (domienderle) [inline src/main/kotlin/se/uulm/snowballr/backend/db/Database.kt]:
```suggestion
     * This method checks if a dummy user is needed based on the environment settings. If so, it
     * creates the dummy user if it does not already exist. If the dummy user is not needed, it
     * deletes the dummy user from the database, in case it already exists.
```

File: src/main/kotlin/se/uulm/snowballr/backend/db/Database.kt [hunk 2]
```diff
@@ -125,29 +125,40 @@ class Database(
...
+                it[passwordHash] = DummyUser.passwordHash
+                it[role] = DummyUser.role
+                it[status] = DummyUser.status
+            }.value
+
+            logger.info { "Dummy User ID: ${DummyUser.id}, Password: ${DummyUser.password}" }
+        } else {
+            // If the dummy user is not needed, delete it if it exists
+            if (existingId != null) {
+                UserTable.deleteWhere { UserTable.id eq existingId }.also {
```
Comment (domienderle) [inline src/main/kotlin/se/uulm/snowballr/backend/db/Database.kt]: By using `else if` you can safe on stage of nesting.
```suggestion
} else if (existingId != null) {
    // If the dummy user is not needed, delete it if it exists
    UserTable.deleteWhere { UserTable.id eq existingId }.also {
```

**Review by domienderle — CHANGES_REQUESTED** [review]
Looks good so far. Only small things left.

File: src/main/kotlin/se/uulm/snowballr/backend/auth/JwtService.kt
Comment (mowi12) [reply src/main/kotlin/se/uulm/snowballr/backend/auth/JwtService.kt:1]: I only moved it out, since IntelliJ gave warning, but I researched this case and found out that the old version is the more idiomatic version. I will revert these changes.

Comment (domienderle) [reply src/main/kotlin/se/uulm/snowballr/backend/auth/JwtService.kt:1]: All right. Thanks.

**Comment by domienderle** [comment]
Looks good. Let's merge this.

**Review by domienderle — APPROVED** [review]
