### PR TITLE
Prevent duplicate invitations

### LINKED ISSUE #360: [Bug]: When I invite a user twice, then only a meaningless `INTERNAL` error is returned
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which use case does this bug relate to?

_No response_

### What happened?

When I invite the same user twice to a project, no matter whether the invitation token has expired or not, then I get an `INTERNAL` error without any meaningful error message.

### Steps to reproduce

1. Invite a user to project (using `inviteUserToProject`)
2. Submit the same request a second time

### What did you expect?

The server should check, whether the invitation token can be saved or the unique constraint is violated (further discussion about the unique constraint is required in the case, when the token is expired) and in the error case return a more meaningful error than: 'Unknown error occurred during request execution: "INTERNAL: An unexpected error occurred"'.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Merseleo**
Closes #360 

## What I have made

- I added a check that runs before a user is invited that check, whether a user was already invited and a invitation token already exists.
- I added a test for this case and improved the `inviteUserToProject` service tests

## Checklist

Either tick or cross out the items that do not apply (using \~\~example text\~\~) and give a reason why the item does
not apply.

- [x] I have updated the documentation accordingly and commented my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] (for reviewer) I have checked the implementation against the requirements

### CODE REVIEW

File: src/main/kotlin/se/uulm/snowballr/backend/service/InvitationService.kt [hunk 1]
```diff
@@ -132,7 +141,7 @@ class InvitationService(
             ),
         )
 
-        return Base.Nothing.getDefaultInstance()
+        return@withUser Base.Nothing.getDefaultInstance()
```
Comment (Slartibartfass2) [inline src/main/kotlin/se/uulm/snowballr/backend/service/InvitationService.kt]:
```suggestion
        Base.Nothing.getDefaultInstance()
```

File: src/main/kotlin/se/uulm/snowballr/backend/service/InvitationService.kt [hunk 2]
```diff
@@ -110,6 +109,16 @@ class InvitationService(
 
         isProjectActive().checkFor(currentUser, project)
 
+        // Check if the user is already invited
+        val isAlreadyInvited = invitationTokenRepo.getInvitationTokenByEmailAndProjectId(
+            request.userEmail,
+            projectId,
+        ).isSuccess
```
Comment (Slartibartfass2) [inline src/main/kotlin/se/uulm/snowballr/backend/service/InvitationService.kt]:
```suggestion
        val isAlreadyInvited =
            invitationTokenRepo.getInvitationTokenByEmailAndProjectId(request.userEmail, projectId).isSuccess
```

File: src/main/kotlin/se/uulm/snowballr/backend/service/InvitationService.kt [hunk 3]
```diff
@@ -110,6 +109,16 @@ class InvitationService(
...
+        if (isAlreadyInvited) {
+            Logger.warn { "The user ${request.userEmail} was already invited to the project $projectId." }
+            return@withUser Base.Nothing.getDefaultInstance()
+        }
```
Comment (Slartibartfass2) [inline src/main/kotlin/se/uulm/snowballr/backend/service/InvitationService.kt:117]: I don't think it's necessary to log this since we defined this behavior in the API docs.

**Review by Slartibartfass2 — CHANGES_REQUESTED** [review]
Great work. Only these debatable changes.

File: src/main/kotlin/se/uulm/snowballr/backend/service/InvitationService.kt (hunk 1 above)
Comment (Merseleo) [reply src/main/kotlin/se/uulm/snowballr/backend/service/InvitationService.kt]: Ah ok, I thought the return@withUser was necessary like in the first return.

File: src/main/kotlin/se/uulm/snowballr/backend/service/InvitationService.kt (hunk 3 above)
Comment (Merseleo) [reply src/main/kotlin/se/uulm/snowballr/backend/service/InvitationService.kt:117]: Ok, i thought that it could be helpful to understand whether an invitation was received successfully but is a duplicate or whether something went wrong, but I also understand that we can ignore this.

**Review by Merseleo — COMMENTED** [review]
Thank you for the review, I hope I implemented the changes correctly.

**Review by Slartibartfass2 — APPROVED** [review]
